package com.sosuisha.service;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.nio.file.Files;
import java.nio.file.Path;

import org.jaudiotagger.audio.AudioFileIO;
import org.jaudiotagger.tag.FieldKey;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class JaudiotaggerTagWriterTest {
    @TempDir
    Path folder;

    @Test
    @DisplayName("mp3のタグにアルバム名とアルバムアーティストを書き込み、年は保持される")
    void writes_album_name_and_album_artist_to_the_tag_of_an_mp3_file_keeping_the_year()
        throws Exception {
        // tagged.mp3 (year 2020) is generated by helpers/make-tagged-mp3.ps1.
        var file = folder.resolve("tagged.mp3");
        Files.copy(Path.of("src/test/resources/id3/tagged.mp3"), file);

        new JaudiotaggerTagWriter().writeAlbumTag(file, "New Album", "New Artist");

        var tag = AudioFileIO.read(file.toFile()).getTag();
        assertEquals("New Album", tag.getFirst(FieldKey.ALBUM));
        assertEquals("New Artist", tag.getFirst(FieldKey.ALBUM_ARTIST));
        assertEquals("2020", tag.getFirst(FieldKey.YEAR));
    }

    @Test
    @DisplayName("m4aのタグにアルバム名とアルバムアーティストを書き込み、年は保持される")
    void writes_album_name_and_album_artist_to_the_tag_of_an_m4a_file_keeping_the_year()
        throws Exception {
        // tagged.m4a (year 2015) is generated by helpers/make-tagged-m4a.ps1 (requires ffmpeg).
        var file = folder.resolve("tagged.m4a");
        Files.copy(Path.of("src/test/resources/id3/tagged.m4a"), file);

        new JaudiotaggerTagWriter().writeAlbumTag(file, "New Album", "New Artist");

        var tag = AudioFileIO.read(file.toFile()).getTag();
        assertEquals("New Album", tag.getFirst(FieldKey.ALBUM));
        assertEquals("New Artist", tag.getFirst(FieldKey.ALBUM_ARTIST));
        assertEquals("2015", tag.getFirst(FieldKey.YEAR));
    }
}
