package com.sosuisha.service;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.nio.file.Files;
import java.nio.file.Path;

import org.jaudiotagger.audio.AudioFileIO;
import org.jaudiotagger.tag.FieldKey;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class JaudiotaggerTagWriterTest {
    @TempDir
    Path folder;

    @Test
    @DisplayName("mp3のタグにアルバム名・アルバムアーティスト・年を書き込める")
    void writes_album_name_album_artist_and_year_to_the_tag_of_an_mp3_file() throws Exception {
        // tagged.mp3 is generated by helpers/make-tagged-mp3.ps1.
        var file = folder.resolve("tagged.mp3");
        Files.copy(Path.of("src/test/resources/id3/tagged.mp3"), file);

        new JaudiotaggerTagWriter().writeAlbumTag(file, "New Album", "New Artist", "2021");

        var tag = AudioFileIO.read(file.toFile()).getTag();
        assertEquals("New Album", tag.getFirst(FieldKey.ALBUM));
        assertEquals("New Artist", tag.getFirst(FieldKey.ALBUM_ARTIST));
        assertEquals("2021", tag.getFirst(FieldKey.YEAR));
    }

    @Test
    @DisplayName("m4aのタグにアルバム名・アルバムアーティスト・年を書き込める")
    void writes_album_name_album_artist_and_year_to_the_tag_of_an_m4a_file() throws Exception {
        // tagged.m4a is generated by helpers/make-tagged-m4a.ps1 (requires ffmpeg).
        var file = folder.resolve("tagged.m4a");
        Files.copy(Path.of("src/test/resources/id3/tagged.m4a"), file);

        new JaudiotaggerTagWriter().writeAlbumTag(file, "New Album", "New Artist", "2021");

        var tag = AudioFileIO.read(file.toFile()).getTag();
        assertEquals("New Album", tag.getFirst(FieldKey.ALBUM));
        assertEquals("New Artist", tag.getFirst(FieldKey.ALBUM_ARTIST));
        assertEquals("2021", tag.getFirst(FieldKey.YEAR));
    }
}
