package com.sosuisha.service;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.FileTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import com.sosuisha.domain.model.MusicFile;
import com.sosuisha.domain.model.TrackMetadata;
import com.sosuisha.domain.service.NullLibraryDatabase;

class LibraryIndexerTest {
    @TempDir
    Path folder;

    @Test
    @DisplayName("フォルダパスを指定すると、フォルダ直下とサブフォルダ内の対応形式のみのパスのリストを返す")
    void returns_paths_of_only_supported_formats_in_the_folder_and_subfolders() throws Exception {
        var first = Files.createFile(folder.resolve("first.mp3"));
        Files.createFile(folder.resolve("second.txt"));
        var sub = Files.createDirectory(folder.resolve("sub"));
        var third = Files.createFile(sub.resolve("third.mp3"));

        var scanner = new LibraryIndexer(new NullLibraryDatabase());
        var musicFiles = scanner.scan(folder);

        assertEquals(
            List.of(first, third),
            musicFiles.stream().map(MusicFile::path).sorted().toList()
        );
    }

    @Test
    @DisplayName("大文字の拡張子のファイルも取得できる")
    void returns_files_with_uppercase_extension() throws Exception {
        var upper = Files.createFile(folder.resolve("fourth.MP3"));

        var scanner = new LibraryIndexer(new NullLibraryDatabase());
        var musicFiles = scanner.scan(folder);

        assertEquals(List.of(upper), musicFiles.stream().map(MusicFile::path).toList());
    }

    @Test
    @DisplayName("mp3ファイルを取得できる")
    void returns_mp3_files() throws Exception {
        var mp3 = Files.createFile(folder.resolve("first.mp3"));

        var scanner = new LibraryIndexer(new NullLibraryDatabase());
        var musicFiles = scanner.scan(folder);

        assertEquals(List.of(mp3), musicFiles.stream().map(MusicFile::path).toList());
    }

    @Test
    @DisplayName("m4aファイルを取得できる")
    void returns_m4a_files() throws Exception {
        var m4a = Files.createFile(folder.resolve("fifth.m4a"));

        var scanner = new LibraryIndexer(new NullLibraryDatabase());
        var musicFiles = scanner.scan(folder);

        assertEquals(List.of(m4a), musicFiles.stream().map(MusicFile::path).toList());
    }

    @Test
    @DisplayName("先頭が.で始まる隠しファイルはスキップされる")
    void skips_hidden_files_whose_names_start_with_a_dot() throws Exception {
        var visible = Files.createFile(folder.resolve("song.mp3"));
        Files.createFile(folder.resolve(".hidden.mp3"));

        var scanner = new LibraryIndexer(new NullLibraryDatabase());
        var musicFiles = scanner.scan(folder);

        assertEquals(List.of(visible), musicFiles.stream().map(MusicFile::path).toList());
    }

    @Test
    @DisplayName("ロードしたmp3ファイルのMusicFileにID3タグが含まれる")
    void music_file_of_loaded_mp3_file_contains_id3_tag() throws Exception {
        // The mp3 files in src/test/resources/id3 and their ID3 tag values are
        // generated by helpers/make-tagged-mp3.ps1.
        var scanner = new LibraryIndexer(new NullLibraryDatabase());
        var musicFiles = scanner.scan(Path.of("src/test/resources/id3"));

        assertEquals(
            new TrackMetadata(
                "Test Song", "Test Artist", "Test Album", "Test Album Artist", "3", "2020"
            ),
            findByFileName(musicFiles, "tagged.mp3").tag()
        );
        assertEquals(
            new TrackMetadata(
                "Another Song", "Another Artist", "Another Album", "Another Album Artist",
                "7", "1999"
            ),
            findByFileName(musicFiles, "tagged2.mp3").tag()
        );
    }

    @Test
    @DisplayName("ロードしたm4aファイルのMusicFileにメタデータが含まれる")
    void music_file_of_loaded_m4a_file_contains_metadata() throws Exception {
        // tagged.m4a is generated by helpers/make-tagged-m4a.ps1 (ffmpeg required).
        var scanner = new LibraryIndexer(new NullLibraryDatabase());
        var musicFiles = scanner.scan(Path.of("src/test/resources/id3"));

        assertEquals(
            new TrackMetadata(
                "M4A Song", "M4A Artist", "M4A Album", "M4A Album Artist", "5", "2015"
            ),
            findByFileName(musicFiles, "tagged.m4a").tag()
        );
    }

    @Test
    @DisplayName("タグの無い・解析できないファイルは空文字タグになる")
    void file_without_readable_tag_has_empty_string_metadata() throws Exception {
        var file = folder.resolve("broken.mp3");
        Files.write(file, new byte[10]);

        var scanner = new LibraryIndexer(new NullLibraryDatabase());
        var musicFiles = scanner.scan(folder);

        assertEquals(TrackMetadata.EMPTY, musicFiles.get(0).tag());
    }

    @Test
    @DisplayName("タグの無い正常なファイルは空文字タグになる")
    void valid_file_without_tag_has_empty_string_metadata() throws Exception {
        // untagged.mp3 (valid MPEG frames without any tag) is generated by
        // helpers/make-tagged-mp3.ps1.
        var scanner = new LibraryIndexer(new NullLibraryDatabase());
        var musicFiles = scanner.scan(Path.of("src/test/resources/id3"));

        assertEquals(TrackMetadata.EMPTY, findByFileName(musicFiles, "untagged.mp3").tag());
    }

    private static MusicFile findByFileName(List<MusicFile> musicFiles, String fileName) {
        return musicFiles.stream()
            .filter(file -> file.path().getFileName().toString().equals(fileName))
            .findFirst()
            .orElseThrow();
    }

    @Test
    @DisplayName("キャッシュヒットしたらキャッシュのメタデータを利用する")
    void scan_uses_cached_metadata_on_cache_hit() throws Exception {
        var file = folder.resolve("first.mp3");
        Files.write(file, new byte[123]);
        var cached = new TrackMetadata(
            "Cached Song", "Cached Artist", "Cached Album", "Cached Album Artist", "1", "2001"
        );
        var database = new NullLibraryDatabase() {
            @Override
            public Optional<TrackMetadata> find(Path path, long size, FileTime lastModified) {
                return Optional.of(cached);
            }
        };

        var musicFiles = new LibraryIndexer(database).scan(folder);

        assertEquals(cached, musicFiles.get(0).tag());
    }

    @Test
    @DisplayName("キャッシュがヒットしなかった場合、ロードしたメタデータをDBに保存する")
    void scan_saves_loaded_metadata_to_the_database_on_cache_miss() throws Exception {
        // tagged.mp3 and its tag values are generated by helpers/make-tagged-mp3.ps1.
        var file = Files.copy(
            Path.of("src/test/resources/id3/tagged.mp3"), folder.resolve("tagged.mp3")
        );
        // An explicit past time proves that the saved lastModified is the
        // modification time of the file, not its creation time (= now).
        var lastModified = FileTime.fromMillis(1_000_000_000L);
        Files.setLastModifiedTime(file, lastModified);
        var saved = new ArrayList<List<Object>>();
        var database = new NullLibraryDatabase() {
            @Override
            public void save(MusicFile musicFile, FileTime lastModified) {
                saved.add(List.of(musicFile, lastModified));
            }
        };

        new LibraryIndexer(database).scan(folder);

        assertEquals(
            List.of(
                List.of(
                    new MusicFile(
                        file, Files.size(file), new TrackMetadata(
                            "Test Song", "Test Artist", "Test Album", "Test Album Artist", "3",
                            "2020"
                        )
                    ),
                    lastModified
                )
            ),
            saved
        );
    }

    @Test
    @DisplayName("スキャン時に、読み込むファイルのパスが順にコールバックへ通知される")
    void scan_notifies_the_path_of_each_file_being_read_to_the_callback() throws Exception {
        var first = Files.createFile(folder.resolve("first.mp3"));
        var second = Files.createFile(folder.resolve("second.mp3"));
        var notified = new ArrayList<Path>();

        new LibraryIndexer(new NullLibraryDatabase()).scan(folder, notified::add);

        assertEquals(List.of(first, second), notified.stream().sorted().toList());
    }

    @Test
    @DisplayName("走査結果の各ファイルは、そのファイルサイズを持つ")
    void each_scanned_file_has_its_file_size() throws Exception {
        var file = folder.resolve("first.mp3");
        Files.write(file, new byte[123]);

        var scanner = new LibraryIndexer(new NullLibraryDatabase());
        List<MusicFile> musicFiles = scanner.scan(folder);

        assertEquals(List.of(new MusicFile(file, 123)), musicFiles);
    }
}
