package com.sosuisha.presentation.screens.albumedit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.atomic.AtomicBoolean;

import org.jaudiotagger.audio.AudioFileIO;
import org.jaudiotagger.tag.FieldKey;
import org.junit.jupiter.api.io.TempDir;

import com.sosuisha.domain.model.Album;
import com.sosuisha.domain.model.MusicFile;
import com.sosuisha.domain.model.TrackMetadata;
import com.sosuisha.domain.service.NullLibraryRepository;
import com.sosuisha.presentation.appmodel.MusicLibraryAppModel;
import com.sosuisha.service.JaudiotaggerTagWriter;
import com.sosuisha.service.LibraryIndexer;
import javafx.beans.property.SimpleObjectProperty;

class AlbumEditViewModelTest {
    @Test
    @DisplayName("アルバムを選択すると、編集用のアルバム名とアルバムアーティストに選択中のアルバムの値が入る")
    void the_editable_album_name_and_album_artist_hold_the_values_of_the_selected_album() {
        var appModel = new MusicLibraryAppModel(
            new LibraryIndexer(new NullLibraryRepository()),
            new SimpleObjectProperty<>()
        );
        var viewModel = new AlbumEditViewModel(appModel, (_, _, _) -> {
        });

        appModel.selectAlbum(new Album("Album A", "Artist X", List.of()));

        assertEquals("Album A", viewModel.albumNameProperty().get());
        assertEquals("Artist X", viewModel.albumArtistProperty().get());
    }

    @Test
    @DisplayName("アルバムアーティストが空のアルバムを選択すると、編集用のアルバムアーティストに最初の曲のアーティスト名が自動入力される")
    void the_editable_album_artist_is_auto_filled_with_the_artist_of_the_first_track() {
        var appModel = new MusicLibraryAppModel(
            new LibraryIndexer(new NullLibraryRepository()),
            new SimpleObjectProperty<>()
        );
        var viewModel = new AlbumEditViewModel(appModel, (_, _, _) -> {
        });
        var first = new MusicFile(
            Path.of("a/one.mp3"), 100,
            new TrackMetadata("Song One", "Artist X", "Album A", "", "1", "")
        );

        appModel.selectAlbum(new Album("Album A", "", List.of(first)));

        assertEquals("Artist X", viewModel.albumArtistProperty().get());
    }

    @Test
    @DisplayName("編集用のアルバム名をアルバムの元の値と異なる値にすると、albumNameChangedがtrueになる")
    void album_name_changed_is_true_when_the_editable_album_name_differs_from_the_album() {
        var appModel = new MusicLibraryAppModel(
            new LibraryIndexer(new NullLibraryRepository()),
            new SimpleObjectProperty<>()
        );
        var viewModel = new AlbumEditViewModel(appModel, (_, _, _) -> {
        });
        appModel.selectAlbum(new Album("Album A", "Artist X", List.of()));

        viewModel.albumNameProperty().set("New Album");

        assertTrue(viewModel.albumNameChangedProperty().get());
    }

    @Test
    @DisplayName("アルバムアーティストが自動入力されたとき、albumArtistChangedはtrueである")
    void album_artist_changed_is_true_when_the_album_artist_is_auto_filled() {
        var appModel = new MusicLibraryAppModel(
            new LibraryIndexer(new NullLibraryRepository()),
            new SimpleObjectProperty<>()
        );
        var viewModel = new AlbumEditViewModel(appModel, (_, _, _) -> {
        });
        var first = new MusicFile(
            Path.of("a/one.mp3"), 100,
            new TrackMetadata("Song One", "Artist X", "Album A", "", "1", "")
        );

        appModel.selectAlbum(new Album("Album A", "", List.of(first)));

        assertTrue(viewModel.albumArtistChangedProperty().get());
    }

    @Test
    @DisplayName("Saveすると、アルバムの全トラックのタグに編集内容が書き込まれる")
    void saving_writes_the_edited_metadata_to_the_tags_of_all_tracks(@TempDir Path folder)
        throws Exception {
        // tagged.mp3 and tagged2.mp3 are generated by helpers/make-tagged-mp3.ps1.
        var fileA = folder.resolve("one.mp3");
        var fileB = folder.resolve("two.mp3");
        Files.copy(Path.of("src/test/resources/id3/tagged.mp3"), fileA);
        Files.copy(Path.of("src/test/resources/id3/tagged2.mp3"), fileB);
        var appModel = new MusicLibraryAppModel(
            new LibraryIndexer(new NullLibraryRepository()),
            new SimpleObjectProperty<>()
        );
        var viewModel = new AlbumEditViewModel(appModel, new JaudiotaggerTagWriter());
        var trackA = new MusicFile(fileA, Files.size(fileA));
        var trackB = new MusicFile(fileB, Files.size(fileB));
        appModel.selectAlbum(
            new Album("Test Album", "Test Album Artist", List.of(trackA, trackB))
        );
        viewModel.albumNameProperty().set("New Album");
        viewModel.albumArtistProperty().set("New Artist");

        viewModel.save();

        var tagA = AudioFileIO.read(fileA.toFile()).getTag();
        assertEquals("New Album", tagA.getFirst(FieldKey.ALBUM));
        assertEquals("New Artist", tagA.getFirst(FieldKey.ALBUM_ARTIST));
        var tagB = AudioFileIO.read(fileB.toFile()).getTag();
        assertEquals("New Album", tagB.getFirst(FieldKey.ALBUM));
        assertEquals("New Artist", tagB.getFirst(FieldKey.ALBUM_ARTIST));
    }

    @Test
    @DisplayName("Saveすると、ライブラリ変更フラグが立つ")
    void saving_sets_the_library_changed_flag() {
        var appModel = new MusicLibraryAppModel(
            new LibraryIndexer(new NullLibraryRepository()),
            new SimpleObjectProperty<>()
        );
        var viewModel = new AlbumEditViewModel(appModel, (_, _, _) -> {
        });
        appModel.selectAlbum(new Album("Album A", "Artist X", List.of()));
        viewModel.albumNameProperty().set("New Album");

        viewModel.save();

        assertTrue(viewModel.libraryChangedProperty().get());
    }

    @Test
    @DisplayName("Saveすると、変更プロパティはすべてfalseになる")
    void saving_clears_all_changed_properties() {
        var appModel = new MusicLibraryAppModel(
            new LibraryIndexer(new NullLibraryRepository()),
            new SimpleObjectProperty<>()
        );
        var viewModel = new AlbumEditViewModel(appModel, (_, _, _) -> {
        });
        appModel.selectAlbum(new Album("Album A", "Artist X", List.of()));
        viewModel.albumNameProperty().set("New Album");
        viewModel.albumArtistProperty().set("New Artist");

        viewModel.save();

        assertFalse(viewModel.albumNameChangedProperty().get());
        assertFalse(viewModel.albumArtistChangedProperty().get());
    }

    @Test
    @DisplayName("編集ウィンドウを開くと、ライブラリ変更フラグが落ちる")
    void opening_the_window_clears_the_library_changed_flag() {
        var appModel = new MusicLibraryAppModel(
            new LibraryIndexer(new NullLibraryRepository()),
            new SimpleObjectProperty<>()
        );
        var viewModel = new AlbumEditViewModel(appModel, (_, _, _) -> {
        });
        appModel.selectAlbum(new Album("Album A", "Artist X", List.of()));
        viewModel.save();

        viewModel.windowOpened();

        assertFalse(viewModel.libraryChangedProperty().get());
    }

    @Test
    @DisplayName("ライブラリ変更フラグが立っているとき、編集ウィンドウを閉じるとライブラリが再スキャンされる")
    void closing_the_window_rescans_the_library_when_the_library_changed_flag_is_set() {
        var rescanned = new AtomicBoolean(false);
        var appModel = new MusicLibraryAppModel(
            new LibraryIndexer(new NullLibraryRepository()),
            new SimpleObjectProperty<>()
        ) {
            @Override
            public void rescan() {
                rescanned.set(true);
            }
        };
        var viewModel = new AlbumEditViewModel(appModel, (_, _, _) -> {
        });
        appModel.selectAlbum(new Album("Album A", "Artist X", List.of()));
        viewModel.save();

        viewModel.windowClosed();

        assertTrue(rescanned.get());
    }

}
